/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloStatefulJNI */

#ifndef _Included_HelloStatefulJNI
#define _Included_HelloStatefulJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloStatefulJNI
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_HelloStatefulJNI_malloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     HelloStatefulJNI
 * Method:    putInt
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_HelloStatefulJNI_putInt
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     HelloStatefulJNI
 * Method:    getInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_HelloStatefulJNI_getInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     HelloStatefulJNI
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_HelloStatefulJNI_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
