/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    getNativeBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HelloJNI_getNativeBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HelloJNI
 * Method:    getNativeByte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_HelloJNI_getNativeByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     HelloJNI
 * Method:    getNativeChar
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_HelloJNI_getNativeChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     HelloJNI
 * Method:    getNativeShort
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_HelloJNI_getNativeShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     HelloJNI
 * Method:    getNativeInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_getNativeInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     HelloJNI
 * Method:    getNativeLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_HelloJNI_getNativeLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     HelloJNI
 * Method:    getNativeFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_HelloJNI_getNativeFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     HelloJNI
 * Method:    getNativeDouble
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_HelloJNI_getNativeDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     HelloJNI
 * Method:    getNativeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJNI_getNativeString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloJNI
 * Method:    getNativeDoubleArray
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_HelloJNI_getNativeDoubleArray
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
